export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_FORGOT = 'AUTH_FORGOT'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_LOGIN_START = 'AUTH_LOGIN_START'
export const AUTH_USER_PROFILE = 'AUTH_USER_PROFILE'
export const AUTH_NEED_BACK = 'AUTH_NEED_BACK'

export const NONE = 'NONE'
export const LOADING = 'LOADING'
export const LOADING_FACEBOOK = 'LOADING_FACEBOOK'
export const LOADING_GOOGLE = 'LOADING_GOOGLE'
export const SUCCESS = 'SUCCESS'
export const FAILED = 'FAILED'