export const COTRAVELLER_GET = 'COTRAVELLER_GET'
export const COTRAVELLER_CREATE = 'COTRAVELLER_CREATE'
export const COTRAVELLER_UPDATE = 'COTRAVELLER_UPDATE'
export const COTRAVELLER_DELETE = 'COTRAVELLER_DELETE'

export const NONE = 'NONE'
export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const FAILED = 'FAILED'