export default mapping = {
	"Front desk":require('@images/svg/'+"Front-desk-svg.png"),
	"Room Service":require('@images/svg/'+"016-room-service-svg.png"),
	"Gym":require('@images/svg/'+"038-gym-svg.png"),
	"Security":require('@images/svg/'+"Security-svg.png"),
	"Restaurant":require('@images/svg/'+"015-restaurant-svg.png"),
	"Disabled Friendly":require('@images/svg/'+"disabled-svg.png"),
	"Parking":require('@images/svg/'+"car-svg.png"),
	"Pets":require('@images/svg/'+"pets-svg.png"),
	"Air Condition":require('@images/svg/'+"air-conditioner-svg.png"),
	"Transfers":require('@images/svg/'+"car-svg.png"),
	"ATM":require('@images/svg/'+"012-atm-svg.png"),
	"Pool":require('@images/svg/'+"021-swimmer-2-svg.png"),
	"Babysitting service":require('@images/svg/'+"Babysitting-service-svg.png"),
	"Baggage":require('@images/svg/'+"003-luggage-svg.png"),
	"Bar":require('@images/svg/'+"bar-svg.png"),
	"Bathrobe":require('@images/svg/'+"Bathrobes-svg.png"),
	"Bathtub":require('@images/svg/'+"026-hot-tub-svg.png"),
	"Beach":require('@images/svg/'+"039-scuba-diving-svg.png"),
	"Salon":require('@images/svg/'+"Salon-svg.png"),
	"Bottled Water":require('@images/svg/'+"bottled-water-svg.png"),
	"Breakfast":require('@images/svg/'+"014-breakfast-svg.png"),
	"Wifi":require('@images/svg/'+"044-wifi-svg.png"),
	"Front Desk":require('@images/svg/'+"Front-desk-svg.png"),
	"Cot":require('@images/svg/'+"Babysitting-service-svg.png"),
	"Exchange":require('@images/svg/'+"Currency-exchange-svg.png"),
	"Housekeeping":require('@images/svg/'+"007-housekeeping-svg.png"),
	"Double Bed":require('@images/svg/'+"bed-svg.png"),
	"Laundry service":require('@images/svg/'+"Dry-cleaning-svg.png"),
	"Elevator":require('@images/svg/'+"Elevator-svg.png"),
	"Entertainment":require('@images/svg/'+"tennis-court-svg.png"),
	"Family":require('@images/svg/'+"family-room-svg.png"),
	"Fridge":require('@images/svg/'+"Refrigerator-svg.png"),
	"Garden":require('@images/svg/'+"garden-svg.png"),
	"Gift shop":require('@images/svg/'+"gift-svg.png"),
	"Hair Dryer":require('@images/svg/'+"hair-dryer-svg.png"),
	"Safe":require('@images/svg/'+"safety-box-svg.png"),
	"Laundry Service":require('@images/svg/'+"Dry-cleaning-svg.png"),
	"Library":require('@images/svg/'+"004-books-svg.png"),
	"Trasfer":require('@images/svg/'+"car-svg.png"),
	"wifi":require('@images/svg/'+"044-wifi-svg.png"),
	"Pet":require('@images/svg/'+"pets-svg.png"),
	"Sailing":require('@images/svg/'+"029-river-svg.png"),
	"Shower":require('@images/svg/'+"shower-svg.png"),
	"Wake-Up Service":require('@images/svg/'+"Wake-up-svg.png"),
	"Alarm":require('@images/svg/'+"Wake-up-svg.png"),
	"Hairdryer":require('@images/svg/'+"hair-dryer-svg.png"),
	"Hot tub":require('@images/svg/'+"026-hot-tub-svg.png"),
	"Children Playground":require('@images/svg/'+"kids-club-svg.png"),
	"Extra bed":require('@images/svg/'+"bed-svg.png"),
	"Secretarial service":require('@images/svg/'+"009-concierge-svg.png"),
	"Toiletries":require('@images/svg/'+"Toiletries-svg.png"),
	"Waterskiing":require('@images/svg/'+"027-surf-svg.png"),
	"Chidlren Playground":require('@images/svg/'+"kids-club-svg.png")
}
