export const background = require('@images/background.png')
export const offline = require('@images/offline.jpeg')
export const maintenance = require('@images/maintenance.png')
export const transferLoading = require('@images/transfer-loading.png')
export const hotelLoading = require('@images/hotel-loading.png')
export const activityLoading = require('@images/activity-loading.png')
export const carLoading = require('@images/car-loading.png')
export const flightLoading = require('@images/flight-loading.png')
export const busLoading = require('@images/bus-loading.png')
export const logo = require('@images/logo.png')
export const white_logo = require('@images/white_logo.png')
export const homeBack = require('@images/home_back.png')
export const mapPin = require('@images/map-pin.png')
export const emptyAvatar = require('@images/placeholder.jpg')
export const location = require('@images/location.png')
export const hotel1 = require('@images/hotel1.png')
export const aboutus = require('@images/aboutus.png')
export const locationBack = require('@images/location_back.png')
export const seatFacility = require('@images/icons/seatFacility.png')

//tab icons

export const home_grey = require('@images/tabIcons/home_grey.png')
export const home_primary = require('@images/tabIcons/home_primary.png')
export const package_grey = require('@images/tabIcons/package_grey.png')
export const package_primary = require('@images/tabIcons/package_primary.png')
export const hotdeal_grey = require('@images/tabIcons/hotdeal_grey.png')
export const hotdeal_primary = require('@images/tabIcons/hotdeal_primary.png')
export const mycart_grey = require('@images/tabIcons/mycart_grey.png')
export const mycart_primary = require('@images/tabIcons/mycart_primary.png')
export const profile_grey = require('@images/tabIcons/profile_grey.png')
export const profile_primary = require('@images/tabIcons/profile_primary.png')


// other icons
export const sortIcon = require('@images/icons/sortIcon.png')
export const filterIcon = require('@images/icons/filterIcon.png')
export const mapIcon = require('@images/icons/mapIcon.png')
export const bedIcon = require('@images/icons/bed.png')
export const nightIcon = require('@images/icons/night.png')
export const calendarIcon = require('@images/icons/calendar.png')
export const navigationIcon = require('@images/icons/navigation.png')
export const chatIcon = require('@images/icons/chatIcon.png')
export const infoIcon = require('@images/icons/infoIcon.png')
export const primaryInfo = require('@images/icons/primaryInfo.png')
export const removeIcon = require('@images/icons/removeIcon.png')
export const bank = require('@images/icons/bank.png')
export const internet_bank = require('@images/icons/internet_bank.png')
export const card = require('@images/icons/card.png')
export const sadad = require('@images/icons/sadad.png')
export const twoWayIcon = require('@images/icons/two_way.png')
export const whiteTwoWayIcon = require('@images/icons/white_two_way.png')
export const whiteOneWayIcon = require('@images/icons/white_one_way.png')
export const oneWayIcon = require('@images/icons/one_way.png')
export const nileIcon = require('@images/icons/nile.png')
export const oval_landing = require('@images/icons/oval_landing.png')
export const oval_land_off = require('@images/icons/oval_land_off.png')
export const oval_bus = require('@images/icons/oval_bus.png')
export const departIcon = require('@images/icons/depart.png')
export const returnIcon = require('@images/icons/return.png')
export const double_arrow = require('@images/icons/double_arrow.png')
export const facility_primary1 = require('@images/icons/facility_primary1.png')
export const transfer_white = require('@images/icons/transfer_white.png')
export const transfer_grey = require('@images/icons/transfer_grey.png')
export const bed_grey = require('@images/icons/bed_grey.png')
export const meal_grey = require('@images/icons/meal_grey.png')
export const flight_grey = require('@images/icons/flight_grey.png')
export const bus_orange = require('@images/icons/bus_orange.png')
export const question_orange = require('@images/icons/question_orange.png')
export const ac_icon = require('@images/icons/ac.png')
export const doors_icon = require('@images/icons/doors.png')
export const transmission_icon = require('@images/icons/transmission.png')

export const messageBlack = require('@images/icons/message_black.png')
export const messageWhite = require('@images/icons/message_white.png')
export const messageGreen = require('@images/icons/message_green.png')
export const mobileBlack = require('@images/icons/mobile_black.png')
export const mobileWhite = require('@images/icons/mobile_white.png')
export const mobileGreen = require('@images/icons/mobile_green.png')
export const locked = require('@images/icons/locked.png')
export const closeButtonImage = require('@images/icons/ios7-close-empty.png')
export const roomImage = require('@images/room.png')
export const placeholderImage = require('@images/room.png')
export const activityImage = require('@images/activityImage.png')
export const facilityIcon1 = require('@images/facility1.png')
export const avatar = require('@images/avatar.png')

//22,23,21(Thank you, Reservation Page)
export const passCheckedImage = require('@images/icons/Pass.png')
export const checkedIco = require('@images/icons/Checked.png')

export const hotelIco = require('@images/icons/hotel.png')
export const transferIco = require('@images/icons/transfer.png')
export const packageIco = require('@images/icons/package.png')
export const cruiseIco = require('@images/icons/cruise.png')
export const trainIco = require('@images/icons/train.png')
export const carRentalIco = require('@images/icons/car_rental.png')
export const flightIco = require('@images/icons/flight.png')
export const activityIco = require('@images/icons/activity.png')
export const busIco = require('@images/icons/bus.png')

export const hotel_primary = require('@images/icons/hotel_primary.png')
export const bus_primary = require('@images/icons/bus_primary.png')
export const flight_primary = require('@images/icons/flight_primary.png')
export const transfer_primary = require('@images/icons/transfer_primary.png')
export const vehicle_primary = require('@images/icons/vehicle_primary.png')
export const activity_primary = require('@images/icons/activity_primary.png')
export const packagePrimary = require('@images/icons/package_primary.png')
export const man_man = require('@images/icons/man_man.png')
export const man_child = require('@images/icons/man_child.png')
export const man_black = require('@images/icons/man_black.png')
export const child_black = require('@images/icons/child_black.png')
export const transfer_bag = require('@images/icons/transfer_bag.png')
export const transfer_man = require('@images/icons/transfer_man.png')
export const transfer_green_car = require('@images/icons/transfer_green_car.png')
export const benz = require('@images/icons/benz.png')

export const noImage = require('@images/NoImagefound.jpg')
export const noImage2 = require('@images/NoImagefound2.jpg')
export const promotion = require('@images/promotion.png')

//not found
export const notFoundVehicle = require('@images/notFound/vehicle.jpg')